import { StyleSheet } from 'react-native';
import { colors, fonts, radius } from './theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  content: { padding: 20, paddingTop: 60, paddingBottom: 40 },
  header: { flexDirection: 'row', alignItems: 'center', marginBottom: 28, gap: 12 },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: radius.full,
    backgroundColor: colors.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backText: { fontFamily: fonts.body, fontSize: 20, color: colors.text },
  title: { fontFamily: fonts.heading, fontSize: 22, color: colors.text },
  card: { marginBottom: 16 },
  sectionTitle: {
    fontFamily: fonts.heading,
    fontSize: 12,
    color: colors.text3,
    letterSpacing: 0.5,
    marginBottom: 16,
  },
  fieldGap: { gap: 14 },
  row: { flexDirection: 'row', gap: 12 },
  flex1: { flex: 1 },
  label: {
    fontFamily: fonts.bodyMedium,
    fontSize: 12,
    color: colors.text2,
    marginBottom: 6,
  },
  toggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
  },
  toggleLabel: { fontFamily: fonts.body, fontSize: 14, color: colors.text },
  toggleTrack: {
    width: 44,
    height: 24,
    borderRadius: radius.full,
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  toggleThumb: {
    width: 18,
    height: 18,
    borderRadius: radius.full,
    backgroundColor: colors.text,
  },
  optionRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  option: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
  },
  optionActive: {
    borderColor: colors.accent,
    backgroundColor: colors.bg3,
  },
  optionText: { fontFamily: fonts.body, fontSize: 13, color: colors.text2 },
  optionTextActive: { color: colors.accent2 },
  saveBtn: { marginTop: 8 },
  deleteBtn: { marginTop: 8 },
  error: {
    fontFamily: fonts.body,
    fontSize: 13,
    color: colors.danger,
    textAlign: 'center',
    marginBottom: 8,
  },
});
