import { StyleSheet } from 'react-native';
import { colors, fonts, radius } from './theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  content: { padding: 20, paddingTop: 60, paddingBottom: 40 },
  back: { marginBottom: 20 },
  backText: { fontFamily: fonts.body, fontSize: 14, color: colors.accent2 },
  logoArea: { alignItems: 'center', marginBottom: 28, gap: 8 },
  logoPlaceholder: {
    width: 80,
    height: 80,
    borderRadius: radius.lg,
    backgroundColor: colors.card,
    borderWidth: 0.5,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoText: { fontFamily: fonts.heading, fontSize: 28, color: colors.accent2 },
  appName: { fontFamily: fonts.heading, fontSize: 24, color: colors.text },
  tagline: { fontFamily: fonts.body, fontSize: 13, color: colors.text2 },
  versionCard: { marginBottom: 24, gap: 10 },
  versionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  versionLabel: { fontFamily: fonts.body, fontSize: 13, color: colors.text2 },
  versionValue: { fontFamily: fonts.bodyMedium, fontSize: 13, color: colors.text },
  commitHash: { fontFamily: fonts.mono, fontSize: 12, color: colors.accent2 },
  divider: { height: 0.5, backgroundColor: colors.border },
  sectionTitle: {
    fontFamily: fonts.heading,
    fontSize: 13,
    color: colors.text2,
    letterSpacing: 0.5,
    marginBottom: 12,
  },
  membroCard: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 10 },
  membroAvatar: {
    width: 44,
    height: 44,
    borderRadius: radius.full,
    backgroundColor: colors.bg3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  membroAvatarText: { fontFamily: fonts.heading, fontSize: 18, color: colors.accent2 },
  membroNome: { fontFamily: fonts.heading, fontSize: 14, color: colors.text },
  membroRm: { fontFamily: fonts.bodyMedium, fontSize: 12, color: colors.accent2 },
  membroArea: { fontFamily: fonts.body, fontSize: 11, color: colors.text3 },
  stackGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 },
  stackTag: {
    backgroundColor: colors.card,
    borderWidth: 0.5,
    borderColor: colors.border,
    borderRadius: radius.full,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  stackTagText: { fontFamily: fonts.bodyMedium, fontSize: 11, color: colors.accent2 },
  aboutCard: { marginBottom: 24, gap: 10 },
  aboutText: { fontFamily: fonts.body, fontSize: 13, color: colors.text2, lineHeight: 20 },
  footer: {
    textAlign: 'center',
    fontFamily: fonts.body,
    fontSize: 11,
    color: colors.text3,
    marginTop: 8,
  },
});
