import { StyleSheet } from 'react-native';
import { colors, fonts, radius } from '../../src/styles/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  content: { padding: 20, paddingTop: 60, paddingBottom: 40 },
  center: { flex: 1, backgroundColor: colors.bg, alignItems: 'center', justifyContent: 'center' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  greeting: { fontFamily: fonts.body, fontSize: 14, color: colors.text2 },
  name: { fontFamily: fonts.heading, fontSize: 22, color: colors.text },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: radius.full,
    backgroundColor: colors.card,
    borderWidth: 0.5,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { fontFamily: fonts.heading, fontSize: 15, color: colors.accent2 },
  scoreCard: { marginBottom: 24 },
  scoreTitle: {
    fontFamily: fonts.heading,
    fontSize: 14,
    color: colors.text2,
    marginBottom: 16,
    letterSpacing: 0.3,
  },
  scoreContent: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  scoreInfo: { flex: 1, gap: 8 },
  scoreDate: { fontFamily: fonts.body, fontSize: 11, color: colors.text3 },
  scoreDesc: { fontFamily: fonts.body, fontSize: 12, color: colors.text2, lineHeight: 18 },
  noScore: { alignItems: 'center', paddingVertical: 16, gap: 8 },
  noScoreText: { fontFamily: fonts.heading, fontSize: 15, color: colors.text2 },
  noScoreSubtext: { fontFamily: fonts.body, fontSize: 12, color: colors.text3, textAlign: 'center' },
  errorBox: {
    backgroundColor: 'rgba(255,77,106,0.1)',
    borderWidth: 0.5,
    borderColor: 'rgba(255,77,106,0.3)',
    borderRadius: radius.md,
    padding: 12,
    marginBottom: 16,
  },
  errorText: { fontFamily: fonts.body, fontSize: 13, color: colors.danger },
  sectionTitle: {
    fontFamily: fonts.heading,
    fontSize: 13,
    color: colors.text2,
    letterSpacing: 0.5,
    marginBottom: 12,
    marginTop: 8,
  },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 24 },
  gridItem: {
    width: '47%',
    backgroundColor: colors.card,
    borderWidth: 0.5,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: 16,
    alignItems: 'center',
    gap: 8,
  },
  gridIcon: { fontSize: 28 },
  gridLabel: { fontFamily: fonts.bodyMedium, fontSize: 13, color: colors.text },
  barChart: { flexDirection: 'row', justifyContent: 'space-around', height: 100, alignItems: 'flex-end' },
  barItem: { alignItems: 'center', gap: 4, flex: 1 },
  barValue: { fontFamily: fonts.bodyMedium, fontSize: 10, color: colors.text2 },
  barTrack: {
    width: 24,
    height: 70,
    backgroundColor: 'rgba(58,155,220,0.1)',
    borderRadius: radius.sm,
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  barFill: { width: '100%', borderRadius: radius.sm },
  barLabel: { fontFamily: fonts.body, fontSize: 9, color: colors.text3 },
});
